//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.GlyphLoader.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.GlyphLoader.Core.Tests.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;style&gt;dt {{ font-weight: bold; }} svg {{ border: 1px solid #000; }}&lt;/style&gt;&lt;/head&gt;
        ///&lt;body&gt;&lt;h1&gt;Glyph comparison view&lt;/h1&gt;
        ///&lt;dl&gt;&lt;dt&gt;File: &lt;/dt&gt;&lt;dd&gt;{0}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphIndex: &lt;/dt&gt;&lt;dd&gt;{1}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;Typeface: &lt;/dt&gt;&lt;dd&gt;{2}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;dl&gt;&lt;dt&gt;GlyphTypeface: &lt;/dt&gt;&lt;dd&gt;{3}&lt;/dd&gt;&lt;/dl&gt;
        ///&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string GlyphComparison {
            get {
                return ResourceManager.GetString("GlyphComparison", resourceCulture);
            }
        }
    }
}
